CREATE DATABASE IF NOT EXISTS `users`;
CREATE DATABASE IF NOT EXISTS `authentications`;
GRANT ALL PRIVILEGES ON `users`.* TO 'admin'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `authentications`.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;